//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoitureLocation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocationVoituresEntities : DbContext
    {
        public LocationVoituresEntities()
            : base("name=LocationVoituresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_client> t_client { get; set; }
        public virtual DbSet<t_location> t_location { get; set; }
        public virtual DbSet<t_voiture> t_voiture { get; set; }
        public virtual DbSet<t_retour> t_retour { get; set; }
    }
}
