//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoitureLocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_location
    {
        public int id { get; set; }
        public string voiture_num { get; set; }
        public string marque_modele_voiture { get; set; }
        public string client_nom { get; set; }
        public string client_prenom { get; set; }
        public string frais_location { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
    }
}
