//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoitureLocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_voiture
    {
        public int id { get; set; }
        public string voiture_num { get; set; }
        public string voiture_marque { get; set; }
        public string voiture_modele { get; set; }
        public string voiture_immatriculation { get; set; }
        public string disponibilite { get; set; }
    }
}
